version: '3.1'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs


  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - app